### ISSUE TITLE
why rename not pull-request?

### ISSUE THREAD

**Issue by nruth** [thirtysixthspan/descriptive_statistics#32]
As a user I'm confused by your renaming and republication of the descriptive-statistics gem. Why not collaborate on that instead of creating a new gem and repo? Did you try contacting @jtescher ?

What's the difference between this and that? It'd be useful to have an explanation at the top or bottom of the readme about why you've forked it and what the difference in vision is.

Thanks!

**Comment by thirtysixthspan** [comment]
I think you have it backwards. Please review the first commit dates on the two repos.

https://github.com/thirtysixthspan/descriptive_statistics/commit/592f3c913eec183958575afb4b73d1b28ef6d824

https://github.com/jtescher/descriptive-statistics/commit/d71145763b6ea2d4ff6c02df0c1690a5ed2f8349

**Comment by nruth** [comment]
My mistake! Sorry about that.
