### ISSUE TITLE
Gem is inconsistent with Rails methods which lead to really bad behavior.

### ISSUE THREAD

**Issue by vmeyet** [thirtysixthspan/descriptive_statistics#35]
Defining all the `DescriptiveStatistics ` methods on enumerable without namespacing whatsoever can lead to incompatibility with the Rails framework. Given that it is the most used framework in the community, I think this can lead to really nasty bugs.

For instance [Rails already define a method `sum` on `Enumerable`](http://api.rubyonrails.org/classes/Enumerable.html#method-i-sum), which is:

```ruby
# File activesupport/lib/active_support/core_ext/enumerable.rb, line 20
def sum(identity = 0, &block)
  if block_given?
    map(&block).sum(identity)
  else
    inject { |sum, element| sum + element } || identity
  end
end
```

and `DescriptiveStatistics#sum` is:

```ruby
  def sum(collection = self, &block)
    values = Support::convert(collection, &block)
    return DescriptiveStatistics.sum_empty_collection_default_value if values.empty?

    return values.reduce(:+)
  end
```

As you can see the behaviour AND the signature is not the same.
Most notably, in rails:
```ruby
[].sum # -> 0
[].sum(3) # -> 3
```

in this gem:
```ruby
[].sum # -> nil
[].sum(3) # -> NoMethodError: undefined method `each' for 3:Fixnum
```

the `0` becoming `nil` is the most concerning for those using both Rails and this gem, since the bug can go undetected for quite a while.

In my opinion, the best approach would be either to namespace/prefix the methods, (or instead of including it as a mixin in Enumerable, having module functions but that's way more restrictive).

What do you think of it? what do you think would be the best solution to it?

**Comment by thirtysixthspan** [comment]
Thank you for submitting an issue. You are correct. There is a section in the readme concerning usage with Rails https://github.com/thirtysixthspan/descriptive_statistics#ruby-on-rails. The suggested practice there is to extend the DescriptiveStatistics module on a collection. Alternatively, you may access the module methods for use directly as described in the readme.

**Comment by vmeyet** [comment]
ok thanks, for the update.

I don't really like when things aren't safe by default, (extending Enumerable/Collection or whatever should be the end user choice IMO). Anyway that's my personal taste.

**Comment by thirtysixthspan** [comment]
I hear you. I just don't think that ActiveSupport is going to change its 'unsafe' behavior.
