### ISSUE TITLE
is this gem still active?

### ISSUE THREAD

**Issue by Rovel** [thirtysixthspan/descriptive_statistics#48]
Hi, I'm looking at the last commit and it was a long time ago, is this project still on use or not?

thanks

**Comment by thirtysixthspan** [comment]
Last commit was 3 years ago, and the test suite is run against Ruby 2.3. Buyer beware when using with newer versions of Ruby. I would welcome PRs that update the gem.

**Comment by Rovel** [comment]
thanks, I ran it yesterday on 2.6.3 and the example in the readme.md gets the same result, but a gem update would be best, r u open to outside pr's?

**Comment by thirtysixthspan** [comment]
Awesome. Yes.  I would welcome PRs that update the gem.

**Comment by Rovel** [comment]
Nice @thirtysixthspan I opened a PR but it seems that travis is getting errors before the ruby config.

can you check the #49 ?

Thanks
