### ISSUE TITLE
(Object doesn't support #inspect) caused by descriptive_statistics

### ISSUE THREAD

**Issue by leithl** [thirtysixthspan/descriptive_statistics#8]
I have a Portfolio model, which has_many AssetWeight models. Upon inclusion of the descriptive_statistics gem, I get a strange error, `(Object doesn't support #inspect)`

Models:

``` ruby
class Portfolio < ActiveRecord::Base
  belongs_to :investment_case
  has_many :asset_weights, :dependent => :destroy
  attr_accessible :name
end

class AssetWeight < ActiveRecord::Base
  belongs_to :portfolios
  belongs_to :asset
  attr_accessible :name, :weight
end

```

Code to cause the error

``` ruby
1.9.3-p392 :001 > p = Portfolio.first
1.9.3-p392 :002 > p.asset_weights
(Object doesn't support #inspect)
 => 

```

It worked fine before adding the gem to my Gemfile. Removing it after stopped the problem also.

**Comment by gollawil** [comment]
Still using rails 3 here. There should be a patch added to the gem instead of expecting users to upgrade.

**Comment by thirtysixthspan** [comment]
@gollawil In Rails 3 you can follow this pattern to use the gem: https://github.com/thirtysixthspan/descriptive_statistics#ruby-on-rails

**Comment by gollawil** [comment]
I ended up calling it this way ``stats = DescriptiveStatistics::Stats.new(data)`` and all is good now. Figuring out this gem was the issue took a while though.
